# Generated by Django 4.1.7 on 2023-03-05 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.FloatField(blank=True, null=True, verbose_name='Age in weeks')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth:')),
                ('pet_breed', models.CharField(blank=True, max_length=30, null=True)),
                ('pet_disc', models.TextField(blank=True, null=True)),
                ('pet_color', models.CharField(blank=True, max_length=100, null=True)),
                ('chip_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Chip Number')),
                ('pet_gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True, verbose_name='Gender')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pet_image1', models.ImageField(blank=True, null=True, upload_to='pet_images/%Y/')),
                ('pet_image2', models.ImageField(blank=True, null=True, upload_to='pet_images/%Y/')),
                ('pet_image3', models.ImageField(blank=True, null=True, upload_to='pet_images/%Y/')),
            ],
        ),
    ]
