# Generated by Django 4.1.7 on 2023-03-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dscription', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('suggest_shot', models.DateField(blank=True, null=True)),
                ('last_shot', models.DateField(blank=True, null=True)),
                ('next_shot', models.DateField(blank=True, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('shot_duration', models.IntegerField(blank=True, null=True, verbose_name='Shot duration in weeks')),
                ('is_adult', models.BooleanField(default=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.pet')),
            ],
        ),
    ]
