# Generated by Django 4.1.7 on 2023-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_pet',
            name='med_type',
            field=models.CharField(blank=True, default='vaccination', max_length=100, null=True),
        ),
    ]
