# Generated by Django 4.1.7 on 2023-03-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0002_medical_pet_med_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_pet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
